filebeat:
  prospectors:
    -
      paths:
        - "/var/log/containers/*.log"
      document_type: kube-logs

output:
  logstash:
    hosts: ['logstash:5044']
    index: filebeat
    timeout: 15

logging:
  level: info