filebeat:
  prospectors:
    -
      paths:
        - "/var/log/containers/*.log"
      document_type: kube-logs
      json:
        message_key: log
        keys_under_root: true
        add_error_key: true
        overwrite_keys: true


output:
  logstash:
    hosts: ['logstash:5044']
    index: filebeat
    timeout: 15

logging:
  level: info