apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: kibana
        image: bryanl/docker-kibana
        env:
        - name: KIBANA_ES_URL
          value: "http://elasticsearch.default.svc.cluster.local:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
  - host: kibana.site.x.pifft.com
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: 80
        path: /
