apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: logstash
        image: bryanl/docker-logstash-velocity2016:stage0
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5044
          name: lumberjack
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    component: elk
    role: logstash
spec:
  selector:
    component: elk
    role: logstash
  ports:
  - name: lumberjack
    port: 5044
    protocol: TCP