apiVersion: v1
kind: ReplicationController
metadata:
  name: sentry
  labels:
    app: sentry
spec:
  replicas: 1
  selector:
    app: sentry
  template:
    metadata:
      labels:
        app: sentry
    spec:
      containers:
      - name: sentry
        image: sentry
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        env:
          - name: SENTRY_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sentry-secret-key
                key: secret.txt
          - name: SENTRY_REDIS_HOST
            value: localhost
          - name: SENTRY_DB_NAME
            value: postgres
          - name: SENTRY_DB_USER
            value: postgres
          - name: SENTRY_POSTGRES_HOST
            value: 127.0.0.1
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
      - name: sentry-cron
        image: sentry
        command:
          - sentry
          - run
          - cron
        env:
          - name: SENTRY_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sentry-secret-key
                key: secret.txt
          - name: SENTRY_REDIS_HOST
            value: localhost
          - name: SENTRY_DB_NAME
            value: postgres
          - name: SENTRY_DB_USER
            value: postgres
          - name: SENTRY_POSTGRES_HOST
            value: 127.0.0.1
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
      - name: sentry-worker
        image: sentry
        command:
          - sentry
          - run
          - worker
        env:
          - name: SENTRY_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: sentry-secret-key
                key: secret.txt
          - name: SENTRY_REDIS_HOST
            value: localhost
          - name: SENTRY_DB_NAME
            value: postgres
          - name: SENTRY_DB_USER
            value: postgres
          - name: SENTRY_POSTGRES_HOST
            value: 127.0.0.1
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
          - name: C_FORCE_ROOT
            value: "1"
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: db
          protocol: TCP
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
      - name: memcached
        image: memcached
        ports:
        - containerPort: 11211
          name: memcached
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sentry
  labels:
    app: sentry
spec:
  selector:
    app: sentry
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sentry-ingress
spec:
  rules:
  - host: sentry.k8sdev
    http:
      paths:
      - backend:
          serviceName: sentry
          servicePort: 80
        path: /
