apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: elasticsearch
      namespace: kube-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: elasticsearch



