- hosts: type_digitalocean_droplet
  become: true
  become_user: root
  roles:
    - { role: common }
  tags:
    - common

- hosts: etcd
  become: true
  become_user: root
  roles:
    - { role: etcd }
  tags:
    - etcd

