apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  namespace: kube-system
  labels:
    component: elk
    role: logstash
spec:
  replicas: 1
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: logstash
        image: bryanl/logstash:2.3.2
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5043
          name: lumberjack
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"